version: '3'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:5000:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: adminpassword
    depends_on:
      - db
    links:
      - db
   
  #wpcli:
    #image: wordpress:cli
    #volumes:
      #- ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      #- ./wp-app:/var/www/html
    #depends_on:
      #- db
      #- wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_PASSWORD: adminpassword
    ports:
      - ${IP}:8080:80
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd # any random string will do
      MYSQL_DATABASE: wordpress # the name of your mysql database
      MYSQL_USER: wp # the name of the database user
      MYSQL_PASSWORD: adminpassword # the password of the mysql user

volumes:
  db_data:
